## Algebra matricial 

Nesse capitulo estudamos a forma de manipular matrices e vetores numéricamente. Usando
esses objetos aprendemos a resolver sistemas de equações lineares que aparecem em
muitas áreas da ciência.

Mesmo estudando a forma de resolver sistemas de equações usando matrizes, não vamos escrever nossas rotinas mas usaremos as rotinas sofisticadas da biblioteca [`numpy.linalg`](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html), estudaremos, no entanto, as bases matemáticas.


###  propriedades matemáticas das matrizes

Trabalharemos com matrizes do tipo  ${\bf A}$ de  $n\times n$ elementos, sendo  ${\bf A}$
real ou complexa. Ex:

$$
\mathbf{A} =
      \begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{14} \\
                                 a_{21} & a_{22} & a_{23} & a_{24} \\
                                   a_{31} & a_{32} & a_{33} & a_{34} \\
                                  a_{41} & a_{42} & a_{43} & a_{44}
             \end{bmatrix}\qquad
\mathbf{I} =
      \begin{bmatrix} 1 & 0 & 0 & 0 \\
                                 0 & 1 & 0 & 0 \\
                                 0 & 0 & 1 & 0 \\
                                 0 & 0 & 0 & 1
             \end{bmatrix}
$$


O inverso dessa matriz, se existe, é tal que ${\bf A}^{-1}\cdot {\bf A} = {\bf I}$. $a_{ij}$ se refer  a um elemento da matriz na fila $i$ e na columna $j$.  Um vetor é um array  unidimensional, ${\bf x}$, da forma:

###  propriedades matemáticas das matrizes


<table border="1" style="width:80%"  >
<thead>
<tr><th align="center">              Relations               </th> <th align="center">      Name     </th> <th align="center">                            matrix elements                            </th> </tr>
</thead>
<tbody>
<tr><td align="center">   $A = A^{T}$ </td> <td align="center">   symmetric  </td> <td align="center">   $a_{ij} = a_{ji}$  </td> </tr>
 
<tr><td align="center">   $A = \left (A^{T} \right )^{-1}$          </td> <td align="center">   real ortogonal    </td> <td align="center">   $\sum_k a_{ik} a_{jk} = \sum_k a_{ki} a_{kj} = \delta_{ij}$                </td> </tr>
<tr><td align="center">   $A = A^{ * }$                             </td> <td align="center">   real matrix        </td> <td align="center">   $a_{ij} = a_{ij}^{ * }$                                                    </td> </tr>
<tr><td align="center">   $A = A^{\dagger}$                         </td> <td align="center">   hermitian          </td> <td align="center">   $a_{ij} = a_{ji}^{ * }$                                                    </td> </tr>
<tr><td align="center">   $A = \left (A^{\dagger} \right )^{-1}$    </td> <td align="center">   unitary            </td> <td align="center">   $\sum_k a_{ik} a_{jk}^{ * } = \sum_k a_{ki}^{ * } a_{kj} = \delta_{ij}$    </td> </tr>
</tbody>
</table>

### Definições:

* **Matriz Hermitiana**: Uma matriz é dita Hermitiana ou auto-adjunta se for idéntica à sua transposta conjugada.
* **Matriz transposta conjugada**: a matriz transposta conjugada da matriz $A$ de $n \times m$ é outra matriz $n \times m$, formada pelo complexo conjugado da matriz transposta, $A^T$. Costuma se denotar por $A^{*}$.



### Algumas matrizes famosas

  * Diagonal if $a_{ij}=0$ for $i\ne j$

  * Upper triangular if $a_{ij}=0$ for $i > j$

  * Lower triangular if $a_{ij}=0$ for $i < j$

  * Tridiagonal if $a_{ij}=0$ for $|i -j| > 1$





### Propriedades das matrizes


Para uma matriz $N\times N$,   $\mathbf{A}$ as seguintes propriedades são todas equivalentes

  * Se a inversa de $\mathbf{A}$ existe, $\mathbf{A}$ é não singular.

  * A equação  $\mathbf{Ax}=0$ implica $\mathbf{x}=0$.

  * As filas de $\mathbf{A}$ formam uma base de $R^N$.

  * As colunas de $\mathbf{A}$ formam uma base de $R^N$.

  * $\mathbf{A}$ é um produto de matrizes elementares.

  * $0$ não é um autovalor de $\mathbf{A}$.

### Operações matemáticas importantes com matrizes

#### Soma e substração 

<!-- Equation labels as ordinary links -->
<div id="eq:mtxadd"></div>
$$
\begin{equation}
\mathbf{A}= \mathbf{B}\pm\mathbf{C}  \Longrightarrow a_{ij} = b_{ij}\pm c_{ij},
\label{eq:mtxadd} \tag{1}
\end{equation}
$$


#### multiplicação escalar-matriz

<!-- Equation labels as ordinary links -->
<div id="_auto1"></div>
$$
\begin{equation}
\mathbf{A}= \gamma\mathbf{B}  \Longrightarrow a_{ij} = \gamma b_{ij},
\label{_auto1} \tag{2}
\end{equation}
$$

#### Multiplicação vetor-matriz

<!-- Equation labels as ordinary links -->
<div id="eq:vecmtx"></div>

$$
\begin{equation}
\mathbf{y}=\mathbf{Ax}   \Longrightarrow y_{i} = \sum_{j=1}^{n} a_{ij}x_j,
\label{eq:vecmtx} \tag{3}
\end{equation}
$$

#### Multiplicação Matriz-Matriz

<!-- Equation labels as ordinary links -->
<div id="eq:mtxmtx"></div>
$$
\begin{equation}
\mathbf{A}=\mathbf{BC}   \Longrightarrow a_{ij} = \sum_{k=1}^{n} b_{ik}c_{kj},
\label{eq:mtxmtx} \tag{4}
\end{equation}
$$

#### Transposição

<!-- Equation labels as ordinary links -->
<div id="_auto2"></div>

$$
\begin{equation}
\mathbf{A}=\mathbf{B}^T   \Longrightarrow a_{ij} = b_{ji}
\label{_auto2} \tag{5}
\end{equation}
$$

### Operações matemáticas importantes com vetores

#### soma e substração

<!-- Equation labels as ordinary links -->
<div id="_auto3"></div>

$$
\begin{equation}
\mathbf{x}= \mathbf{y}\pm\mathbf{z}  \Longrightarrow x_{i} = y_{i}\pm z_{i},
\label{_auto3} \tag{6}
\end{equation}
$$

#### Multiplicação escalar-vetor

<!-- Equation labels as ordinary links -->
<div id="_auto4"></div>

$$
\begin{equation}
\mathbf{x}= \gamma\mathbf{y}  \Longrightarrow x_{i} = \gamma y_{i},
\label{_auto4} \tag{7}
\end{equation}
$$

#### Multiplicação vetor-vetor (multiplicação de Hadamard)

*note que o resultado é um vetor*

<!-- Equation labels as ordinary links -->
<div id="_auto5"></div>

$$
\begin{equation}
\mathbf{x}=\mathbf{yz}   \Longrightarrow x_{i} = y_{i}z_i,
\label{_auto5} \tag{8}
\end{equation}
$$

#### Produto interno ou produto escalar

*o resultado é um escalar*

<!-- Equation labels as ordinary links -->
<div id="eq:innerprod"></div>

$$
\begin{equation}
x=\mathbf{y}^T\mathbf{z}   \Longrightarrow x = \sum_{j=1}^{n} y_{j}z_{j},
\label{eq:innerprod} \tag{9}
\end{equation}
$$

#### Produto externo

*cujo resultado é uma matriz* 

<!-- Equation labels as ordinary links -->
<div id="eq:outerprod"></div>

$$
\begin{equation}
\mathbf{A}=  \mathbf{yz}^T \Longrightarrow  a_{ij} = y_{i}z_{j},
\label{eq:outerprod} \tag{10}
\end{equation}
$$

#### Norma de um vetor 

<!-- Equation labels as ordinary links -->
<div id="eq:norm"></div>
$$
\begin{equation}
|| {\bf x} ||_p = (|x_1|^p + |x_2|^p + ... + |x_n|^p )^{1/p} 
\label{eq:norm} \tag{11}
\end{equation}
$$

#### Relação de Cauchy-Schwartz 

para todo ${\bf x}$ real ou complexo, o produto interno satisfaz:

$$
\begin{equation}
|{\bf x}^T {\bf y}| \le ||x||_2 ||y||_2
\label{eq:cauchy1} \tag{12}
\end{equation}
$$

a partir da qual temos que para todos ${\bf x}$ e ${\bf y}$, o produto escalar satisfaz 

$$
\begin{equation}
||{\bf x} + {\bf y}|| \le ||x||_2 + ||y||_2
\label{eq:cauchy2} \tag{13}
\end{equation}
$$.


### Declaração de matrices 

Em `numpy` declaramos as matrices como arrays multidimensionais:


In [2]:
import numpy as np

In [7]:
A = np.array([[1,3,4],[3,4,6],[4,6,8]])
A

array([[1, 3, 4],
       [3, 4, 6],
       [4, 6, 8]])

In [8]:
B = np.array([2,4,6])
B

array([2, 4, 6])

In [9]:
A.dot(B)

array([38, 58, 80])

Devemos ser cuidadosos ao trabalhar com matrices em Python, pois Python, assim como C e C++, organiza as matrices na memoria considerando primeiro as filas (*row major*). Fortran organiza as matrices começando pelas colunas (*column major*). 

As figuras seguintes ilustram ambos esquemas:


<img src="Figs/decl-both2.png" width=80% >
<img src="Figs/decl-both.png" width=80% >

## Atividade

1. Vamos agora usar a equação (4) para multiplicar duas matrices. Começamos com duas matrices pequenas, a matriz A definida acima, e a matriz C:

In [5]:
C = np.array([[-1,  0,  0.5],[0, -2,  1.5],[ 0.5,  1.5, -1.25]])
C

[[-1.    0.    0.5 ]
 [ 0.   -2.    1.5 ]
 [ 0.5   1.5  -1.25]]


(3, 3)

2. Quando verificarmos que nossa rotina funciona, vamos fazer operações computacionalmente mais exigentes, vamos criar matrizes $n \times n$ com $n = 100$. 

3. Utilizando o módulo `time` vamos comparar a velocidade da função criada por vcs com as rotinas do numpy `matmul` e `dot`. Grafique o tempo usado por cada rotina como função de $n$, para $n=10,100,1000,10000$.

4. Escreva suas conclusões

In [8]:
import time

n = 1000
s = 1./np.sqrt(float(n))
a1 = np.zeros([n,n])

for i in range(n):
    for j in range(n):
        angulo = 2.*np.pi*(i-1)*(j-1)/float(n)
        a1[i,j] = s * (np.sin(angulo) + np.cos(angulo))
        
b1 = np.copy(a1)
t = time.time()
c1 = np.matmul(a1,b1)
t = time.time() - t
print('tempo usado = ', t)

tempo usado =  0.01886749267578125


In [6]:
t = time.time()
d1 = np.dot(a1,b1)
t = time.time() - t
print('tempo usado = ', t)

tempo usado =  0.028328418731689453


In [ ]:
# Função para multiplicar duas matrizes

def mult_mat(A,B):
    # extraimos a dimensão, m x n, da matriz A
    m, n = A.shape
    # e o numero de colunas da matriz B
    p = B.shape[1]

    C = np.zeros((m,p))

    for i in range(0,m):
        for j in range(0,p):
            for k in range(0,n):
                C[i,j] += A[i,k]*B[k,j] 
    return C

## Sistemas lineares

O problema mais básico a ser resolvido usando matrizes é do tipo:

$$
{\bf A} {\bf x} = {\bf b} \;,  \; {\bf A}_{N \times N}  \; {\bf x}_{N \times 1} = {\bf b}_{N \times 1}
$$

As melhores formas de resolver esses sistemas são a decomposição Gaussiana ou a decomposição LU (*lower* -- *upper*). 


Outro método é determinar a matriz inversa de ${\bf A}$, e encontrar a solução multiplicando ambos os lados da equação por ${\bf A}^{-1}$ :

$$
{\bf x} =  {\bf A}^{-1} {\bf b} \;,
$$

**estudaremos métodos para resolver esse tipo de sistemas lineares**

Se o problema a ser resolvido tém a forma:

$$
{\bf A} {\bf x} = \lambda {\bf x} \;,
$$

sendo ${\bf x}$ desconhecido e $\lambda$ um parâmetro desconhecido, o sistema é um problema de  autovalores no qual a solução existe  unicamente para certos valores de  $\lambda$. Usamos a matriz identidade para reescrever a equação como:

$$
[{\bf A} - \lambda {\bf I}] {\bf x} = 0 \;,
$$

O sistema tém a solução trivial ${\bf x} = 0$. Há outra solução que requer a existência de uma condição que proibe multiplicar ambos os lados da equação acima por $[{\bf A} - \lambda {\bf I}]^{-1}$.
(A condição da não existência do inverso).  Essa condição é cumplida quando:

$$
{\rm det}[{\bf A} - \lambda {\bf I}] = 0 \;,
$$

Os valores de $\lambda$ que satisfazem essa condição são os autovalores procurados.

Nesse caso são necessárias rotinas que calculem o determinante de uma matriz e os zeros de um sistema de equações.

**Esse tipo de problema não sera estudado nesse curso.**


## Eliminação Gaussiana

### Substituição *forward* e *backward* 

O método de substituição *forward* e *backward* é o método classico para resolver sistemas de equações. 

Nosso sistema de equações é:

$$
{\bf A} {\bf x} = {\bf w} \;,  D\; {\bf A}_{N \times N}  \; {\bf x}_{N \times 1} = {\bf w}_{N \times 1}
$$ 

A matriz ${\bf A}$ é não singular e que os elementos da diagonal principal não são nulos  (i.e., $a_{ii} \ne 0$). Um exemplo de um sistema com uma matriz $4 \times 4$

$$
\begin{bmatrix}
                           a_{11}& a_{12} &a_{13}& a_{14}\\
                           a_{21}& a_{22} &a_{23}& a_{24}\\
                           a_{31}& a_{32} &a_{33}& a_{34}\\
                           a_{41}& a_{42} &a_{43}& a_{44}\\
                      \end{bmatrix} \begin{bmatrix}
                           x_1\\
                           x_2\\
                           x_3 \\
                           x_4  \\
                      \end{bmatrix}
  =\begin{bmatrix}
                           w_1\\
                           w_2\\
                           w_3 \\
                           w_4\\
                      \end{bmatrix}.
$$

Que pode também ser escrito da forma

$$
a_{11}x_1 +a_{12}x_2 +a_{13}x_3 + a_{14}x_4=w_1 \nonumber
$$

$$
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + a_{24}x_4=w_2 \nonumber
$$

$$
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 + a_{34}x_4=w_3 \nonumber
$$

$$
a_{41}x_1 + a_{42}x_2 + a_{43}x_3 + a_{44}x_4=w_4. \nonumber
$$

A ideia é usar a primeira equação para eliminar $x_1$ das $n-1$ equações restantes. Logo, usamos a segunda equação para eliminar $x_2$ das $n-2$ equações restantes. Com $n-1$ eliminações do tipo encontramos uma matriz triangular da forma:

<!-- Equation labels as ordinary links -->
<div id="eq:gaussbacksub"></div>
\begin{eqnarray}
b_{11}x_1 +b_{12}x_2 +b_{13}x_3 + b_{14}x_4 &=& y_1 \\\nonumber
b_{22}x_2 + b_{23}x_3 + b_{24}x_4 &=& y_2 \\\nonumber
b_{33}x_3 + b_{34}x_4 &=& y_3 \\\nonumber
b_{44}x_4 &=& y_4
\label{eq:gaussbacksub} \tag{14}
\end{eqnarray}

Que pode ser resolvido recursivamente partindo de $x_n$ ($x_4$ para o caso)

Esse processo pode se expressar matematicamente como

<!-- Equation labels as ordinary links -->
<div id="_auto6"></div>

$$
\begin{equation}
   x_m = \frac{1}{b_{mm}}\left(y_m-\sum_{k=m+1}^nb_{mk}x_k\right)\quad m=n-1,n-2,\dots,1.
\label{_auto6} \tag{15}
\end{equation}
$$

Para chegar ao sistema *upper triangular* começãmos elimnando $x_1$ para $j=2,..., n$. Fazemos isso multiplicando a primeira equação por $a_{j1}/a_{11}$ e depois substraindo o resultado da equação $j_{\rm esima}$. 

Para o caso $4 \times 4$ teremos:

$$
\begin{bmatrix}
                           a_{11}& a_{12} &a_{13}& a_{14}\\
                           0& (a_{22}-\frac{a_{21}a_{12}}{a_{11}}) &(a_{23}-\frac{a_{21}a_{13}}{a_{11}}) & (a_{24}-\frac{a_{21}a_{14}}{a_{11}})\\
0& (a_{32}-\frac{a_{31}a_{12}}{a_{11}})& (a_{33}-\frac{a_{31}a_{13}}{a_{11}})& (a_{34}-\frac{a_{31}a_{14}}{a_{11}})\\
0&(a_{42}-\frac{a_{41}a_{12}}{a_{11}}) &(a_{43}-\frac{a_{41}a_{13}}{a_{11}}) & (a_{44}-\frac{a_{41}a_{14}}{a_{11}}) \\
                      \end{bmatrix} \begin{bmatrix}
                           x_1\\
                           x_2\\
                           x_3 \\
                           x_4  \\
                      \end{bmatrix} 
  =\begin{bmatrix}
                           y_1\\
                           w_2^{(2)}\\
                           w_3^{(2)} \\
                           w_4^{(2)}\\
                      \end{bmatrix},
$$

ou

\begin{eqnarray}
b_{11}x_1 +b_{12}x_2 +b_{13}x_3 + b_{14}x_4 &=& y_1 \\\nonumber
a^{(2)}_{22}x_2 + a^{(2)}_{23}x_3 + a^{(2)}_{24}x_4 &=& w^{(2)}_2 \\\nonumber
a^{(2)}_{32}x_2 + a^{(2)}_{33}x_3 + a^{(2)}_{34}x_4 &=& w^{(2)}_3 \\\nonumber
a^{(2)}_{42}x_2 + a^{(2)}_{43}x_3 + a^{(2)}_{44}x_4 &=& w^{(2)}_4, 
\end{eqnarray}


Os novos coeficientes são:

<!-- Equation labels as ordinary links -->
<div id="_auto8"></div>

$$
\begin{equation}
   b_{1k} = a_{1k}^{(1)} \quad k=1,\dots,n,
\label{_auto8} \tag{16}
\end{equation}
$$

Os outros coeficientes serão:

<!-- Equation labels as ordinary links -->
<div id="_auto9"></div>

$$
\begin{equation}
a_{jk}^{(2)} = a_{jk}^{(1)}-\frac{a_{j1}^{(1)}a_{1k}^{(1)}}{a_{11}^{(1)}} \quad j,k=2,\dots,n,
\label{_auto9} \tag{17}
\end{equation}
$$

o novo lado direito da equação é dada por:

<!-- Equation labels as ordinary links -->
<div id="_auto10"></div>

$$
\begin{equation}
y_{1}=w_1^{(1)}, \quad w_j^{(2)} =w_j^{(1)}-\frac{a_{j1}^{(1)}w_1^{(1)}}{a_{11}^{(1)}} \quad j=2,\dots,n.
\label{_auto10} \tag{18}
\end{equation}
$$

O sistema de $x_1, ..., x_n$ desconhecidos transforma-se assim num sistema $(n-1) \times (n-1)$. 

O passo seguinte é eliminar $x_2$ da terceira equação.

Uma expresão geral para substituição direta é:

<!-- Equation labels as ordinary links -->
<div id="_auto11"></div>

$$
\begin{equation}
   a_{jk}^{(m+1)} = a_{jk}^{(m)}-\frac{a_{jm}^{(m)}a_{mk}^{(m)}}{a_{mm}^{(m)}} \quad j,k=m+1,\dots,n,
\label{_auto11} \tag{19}
\end{equation}
$$


com $m=1,\dots,n-1$ e o lado direito dado por

<!-- Equation labels as ordinary links -->
<div id="_auto12"></div>

$$
\begin{equation}
   w_j^{(m+1)} =w_j^{(m)}-\frac{a_{jm}^{(m)}w_m^{(m)}}{a_{mm}^{(m)}}\quad j=m+1,\dots,n.
\label{_auto12} \tag{20}
\end{equation}
$$

Se valores pequenos (ou zeros) aparecem na diagonal da matriz, podem ser removidos reorganizando a matriz e os vetores permutando filas e colunas. Esse procedimento se chama *pivoting*.

**Veja exemplo de pivoting no quadro**


### Resolvendo circuitos com Python


Quando queremos encontrar as correntes que percorrem um circuito encontramos finalmente um sistema de $n$ equações lineares acopladas. No caso, o circuito teria $n$ correntes. 


<img src="Figs/circuit2.gif" width=50% >

Há varias formas de resolver os circuitos de malhas. Um deles é propor direções iniciais arbitrarias para as correntes e considerar que se a corrente chega num nó, ela é positiva, se ela sai do nó, ela é negativa.  

Considerando a conservação da carga aplicamos essa conveção para formular a primeria equação:

$$
I_1 - I_2 - I_3 = 0
$$

Depois criamos loops para passar por cada elemento da nossa malha. Para o caso, a lei física que deve ser respeitada é a seguinte:

$$
\oint_{CF} E \cdot dl = 0
$$

Ou seja, no caso de cada circuito fechado, a soma das tensões deve ser nula.  Aplicamos a lei de Ohm, $V = IR$, para calcular a tensão em cada resistência. 

Começamos desde qualquer ponto seguindo a direção do loop.  Se a direção do loop e a direção sugerida da corrente em cada resistência são iguais, teremos uma queda de potencial.  Se a direção do loop e a direção da corrente são contrarias teremos um ganho de potencial.  

Quanto as fontes, se a fonte vai de $-$ para $+$ na direção do loop, colocamos a voltagem positiva. Se vai de $+$ para $-$, colocamos a voltagem negativa, pois a voltagem esta decaindo. 

Usando essas regras podemos construir as duas equações restantes:

$$
-2 I_1 + 24 - 3 I_2 =0
$$

$$
-6I_3 + 3 I_2 = 0
$$

As trés equações podem ser organizadas em forma matricial:

$$
\begin{bmatrix}
                           1 & -1 & -1 \\
                          -2 & -3 &  0 \\
                           0 &  3 & -6 \\
                      \end{bmatrix} \begin{bmatrix}
                           I_1\\
                           I_2\\
                           I_3 \\
                      \end{bmatrix}
  =\begin{bmatrix}
                           0  \\
                          -24 \\
                           0  \\
                      \end{bmatrix}.
$$

Resolvemos o sistema de equações, se o resultado para alguma corrente for negativo, significa que o nosso chute inicial está errado e a direção de tal corrente é a oposta. 

Utilizamos `numpy.linal.solve` para resolver esse sistema. Tres linhas de código são suficientes para resolver o problema. 

In [3]:
# Solução do sistema de equações encontrado
# no circuito anterior

A = np.array([[1.,-1.,-1.],[-2.,-3.,0],[0.,3.,-6.]])
V = np.array([0.,-24.,0.])
I = np.linalg.solve(A,V)

print('as correntes encontradas sao')
print('I_1 =', I[0])
print('I_2 =', I[1])
print('I_3 =', I[2])

as correntes encontradas sao
I_1 = 6.0
I_2 = 4.0
I_3 = 2.0


**A sugestão inical da direção das correntes estava certa.**

### Atividade 

Encontre as correntes no circuito seguinte, considere as direções iniciais indicadas na figura. 

<img src="Figs/dcp8.gif" width=70% >




### Decomposição LU

É uma forma de eliminção Gaussiana. A ideia é decompor a matriz ${\bf A}$ em termos de uma matriz ${\bf L}$ com elementos só embaixo da diagonal, e uma matriz ${\bf U}$ contendo a diagonal e os elementos acima dela.

$$
\begin{bmatrix}
                          a_{11} & a_{12} & a_{13} & a_{14} \\
                          a_{21} & a_{22} & a_{23} & a_{24} \\
                          a_{31} & a_{32} & a_{33} & a_{34} \\
                          a_{41} & a_{42} & a_{43} & a_{44}
                      \end{bmatrix}
                      = \begin{bmatrix}
                              1  & 0      & 0      & 0 \\
                          l_{21} & 1      & 0      & 0 \\
                          l_{31} & l_{32} & 1      & 0 \\
                          l_{41} & l_{42} & l_{43} & 1
                      \end{bmatrix}
                        \begin{bmatrix}
                          u_{11} & u_{12} & u_{13} & u_{14} \\
                               0 & u_{22} & u_{23} & u_{24} \\
                               0 & 0      & u_{33} & u_{34} \\
                               0 & 0      &  0     & u_{44}
             \end{bmatrix}.
$$

A matriz ${\bf A}$ tem decomposição LU se o seu determinante é diferente de zero. Se a factorização LU existe, e ${\bf A}$ é não singular, o determinante é dado por 

$${\rm det}\{{\bf A}\} = u_{11}u_{22}...u_{nn},$$

a demonstração pode ser encontrada em G. Golub \& C. Van Loan (1996).


O algoritmo para calcular as matrices L e U é simples de construir, porém vamos nos focar na utilidade da decomposição

Queremos resolver um sistema do tipo: ${\bf A} {\bf x} = {\bf w}$, ou

$$
a_{11}x_1 +a_{12}x_2 +a_{13}x_3 + a_{14}x_4=w_1 \nonumber
$$

$$
a_{21}x_1 + a_{22}x_2 + a_{23}x_3 + a_{24}x_4=w_2 \nonumber
$$

$$
a_{31}x_1 + a_{32}x_2 + a_{33}x_3 + a_{34}x_4=w_3 \nonumber
$$

$$
a_{41}x_1 + a_{42}x_2 + a_{43}x_3 + a_{44}x_4=w_4. \nonumber
$$

Usando a decomposição LU escrevemos:

$$
{\bf A} {\bf x} = {\bf L}{\bf U} {\bf x} = {\bf w}
$$

Essa equação pode ser calculada em dois passos:

$$
{\bf L}{\bf y} = {\bf w} \;, {\rm e} \; \; {\bf U}{\bf x} = {\bf y}
$$


Para nosso exemplo $4 \times 4$ temos

\begin{eqnarray}
y_1 &=& w_1 \\\nonumber
l_{21}y_1 + y_2 &=& w_2 \\\nonumber
l_{31}y_1 + l_{32}y_2 + y_3 &=& w_3 \\\nonumber
l_{41}y_1 + l_{42}y_2 + l_{43}y_3 + y_4 &=& w_4.
\end{eqnarray}

Junto com

\begin{eqnarray}
u_{11}x_1 +u_{12}x_2 +u_{13}x_3 + u_{14}x_4 &=& y_1 \\\nonumber
u_{22}x_2 + u_{23}x_3 + u_{24}x_4 &=& y_2 \\\nonumber
u_{33}x_3 + u_{34}x_4 &=& y_3 \\\nonumber
u_{44}x_4 &=& y_4 
\end{eqnarray}


#### Determinante e inverso de uma matriz

A definição do determinante é:

$$
det\{A\}  = \sum_{p} \left( (-1)^p  \prod_{i=1}^n a_{i,{p_i}}  \right)
$$

Onde a soma é calculada sob todas as permutações $p$ do conjunto $\{1, 2, \ldots, n \}$

Já calcular o inverso de uma matriz de una matriz $ n\times n$ é mais difícil:  precisamos calcular o cofactor complementario $a^{ij}$ para cada elemento $a_{ij}$. 

Este é o determinante de ordem $(n-1)$ obtido cobrindo a fila $i$ e a coluna $j$ na qual o elemento $a_{ij}$ aparece.  O inverso é então a transposta da matriz com elementos $(-)^{i+j} a{ij}$. Por exemplo, se

$$
A = \begin{bmatrix}
     a & b\\
     c & d \\
     \end{bmatrix},
$$


$$
A^{-1} = \frac{1}{|A|}
     \begin{bmatrix}
     d & -b\\
     -c & a \\
     \end{bmatrix} = 
     \frac{1}{ad-bc}
     \begin{bmatrix}
     d & -b\\
     -c & a \\
     \end{bmatrix}
$$

Se a matriz for $3 \times 3$:

$$
A = \begin{bmatrix}
     a_{11} & a_{12} & a_{13}\\
     a_{21} & a_{22} & a_{23}\\
     a_{31} & a_{32} & a_{33}\\
     \end{bmatrix},
$$

Os calculos do determinante e a matriz inversa são mais complicados (**veja exemplo no quadro**).

**Um método mais eficiente é necessârio**


Usando o a decomposição **LU** da matriz ${\bf A}$ é mais simples encontrar o determinante.

$$
det\{\bf A\} = det \{\bf L\} \times det \{\bf U\} = det \{\bf U \}
$$

pois os elementos da diagonal de ${\bf L}$ sao igual a 1.
Logo o determinante pode ser calculado como

$$
det\{\bf A\} = \prod_{k=1}^{N} {\bf u}_{kk} \;.
$$

Encontrar a inversa de uma matriz consiste agora em resolver um grupo de equações lineares. Note que se a inversa da matriz existe,  ${\bf A}^{-1} {\bf A} = {\bf I}$. Que pode ser escrito como:

$$
{\bf LUA}^{-1} = {\bf I} \;.
$$ 

Podemos então assumir que a primeira coluna da matriz inversa pode ser escrita como um vetor com componentes desconhecidas:

$$
\mathbf{A}_1^{-1}= \begin{bmatrix}
                              a_{11}^{-1} \\
                              a_{21}^{-1} \\
                              \dots \\
                              a_{n1}^{-1} \\
                    \end{bmatrix},
$$

Então teremoso o seguinte sistema de equações lineares:

$$
\mathbf{LU}\begin{bmatrix}
                              a_{11}^{-1} \\
                              a_{21}^{-1} \\
                              \dots \\
                              a_{n1}^{-1} \\
                    \end{bmatrix} =\begin{bmatrix}
                               1 \\
                              0 \\
                              \dots \\
                              0 \\
                    \end{bmatrix}.
$$

Para a segunda coluna teremos:

$$
\mathbf{LU}\begin{bmatrix}
                              a_{12}^{-1} \\
                              a_{22}^{-1} \\
                              \dots \\
                              a_{n2}^{-1} \\
                    \end{bmatrix}=\begin{bmatrix}
                                0 \\
                              1 \\
                              \dots \\
                              0 \\
                    \end{bmatrix},
$$

E assim suscesivamente até resolvermos $n$ sistemas lineares de equações.


### Calculando a inversa de uma matriz

Encontre a inversa da matriz

$$
A = \begin{bmatrix}
     1 & 3 & 4\\
     3 & 4 & 6\\
     4 & 6 & 8\\
     \end{bmatrix},
$$

Para encontrar a inversa usamos `scipy.linalg`,

In [1]:
import scipy.linalg
import numpy as np

In [2]:
A = np.array([[1.,3.,4.],[3.,4.,6.],[4.,6.,8.]])

In [3]:
P, L, U = scipy.linalg.lu(A)

In [4]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [5]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.25      ,  1.        ,  0.        ],
       [ 0.75      , -0.33333333,  1.        ]])

In [6]:
U

array([[4.        , 6.        , 8.        ],
       [0.        , 1.5       , 2.        ],
       [0.        , 0.        , 0.66666667]])

In [8]:
LU = scipy.linalg.lu_factor(A)
LU

(array([[ 4.        ,  6.        ,  8.        ],
        [ 0.25      ,  1.5       ,  2.        ],
        [ 0.75      , -0.33333333,  0.66666667]]),
 array([2, 2, 2], dtype=int32))

Para encontrar a inversa resolvemos o sistema

$$
{\bf LUA}^{-1} = {\bf I} \;.
$$ 

In [10]:
n=3
I = np.zeros_like(A)
for i in range (n):
    I[i,i] = 1.

In [11]:
Ainv = scipy.linalg.lu_solve(LU, I)

In [12]:
Ainv

array([[-1.00000000e+00,  0.00000000e+00,  5.00000000e-01],
       [ 2.96059473e-16, -2.00000000e+00,  1.50000000e+00],
       [ 5.00000000e-01,  1.50000000e+00, -1.25000000e+00]])

Para verificar que é a inversa de ${\bf A}$ usamos `matmul`

In [13]:
np.matmul(A,Ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Agora vamos encontrar a inversa de uma matriz $4 \times 4$,**

In [14]:
B = np.array([[1.,1.,1.,-1],[1.,1.,-1.,1.],[1.,-1.,1.,1.],[-1.,1.,1.,1.]])

In [15]:
B

array([[ 1.,  1.,  1., -1.],
       [ 1.,  1., -1.,  1.],
       [ 1., -1.,  1.,  1.],
       [-1.,  1.,  1.,  1.]])

In [25]:
LUB = scipy.linalg.lu_factor(B)

In [26]:
LUB

(array([[ 1.,  1.,  1., -1.],
        [ 1., -2.,  0.,  2.],
        [ 1., -0., -2.,  2.],
        [-1., -1., -1.,  4.]]), array([0, 2, 2, 3], dtype=int32))

In [27]:
n=4
I = np.zeros_like(B)
for i in range (n):
    I[i,i] = 1.

In [28]:
Binv = scipy.linalg.lu_solve(LUB, I)

In [29]:
Binv

array([[ 0.25,  0.25,  0.25, -0.25],
       [ 0.25,  0.25, -0.25,  0.25],
       [ 0.25, -0.25,  0.25,  0.25],
       [-0.25,  0.25,  0.25,  0.25]])

In [30]:
np.matmul(B,Binv)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Atividade 

Utilize decomposição LU para resolver o sistema de equações derivado para resolver o  problema de mecânica apresentado na figura seguinte, 

<img src="Figs/Image165.gif" width=70% >

Escreva as equações que mantém o sistema estatico, e encontre as forçãs $F_1$, $F_2$ e $F_3$.


In [33]:
scipy.linalg.lu_solve?