## Algebra matricial 

Nesse capitulo estudamos a forma de manipular matrices e vetores numéricamente. Usando
esses objetos aprendemos como resolver sistemas de equações lineares que aparecem em
muitas áreas da ciência.

Mesmo estudando a forma de resolver sistemas de equações usando matrizes, não vamos escrever nossas rotinas mas usaremos as rotinas sofisticadas da biblioteca [`numpy.linalg`](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html).


###  propriedades matemáticas das matrizes

Trabalharemos com matrizes do tipo  ${\bf A}$ de  $n\times n$ elementos, sendo  ${\bf A}$
real ou complexa. Ex:

$$
\mathbf{A} =
      \begin{bmatrix} a_{11} & a_{12} & a_{13} & a_{14} \\
                                 a_{21} & a_{22} & a_{23} & a_{24} \\
                                   a_{31} & a_{32} & a_{33} & a_{34} \\
                                  a_{41} & a_{42} & a_{43} & a_{44}
             \end{bmatrix}\qquad
\mathbf{I} =
      \begin{bmatrix} 1 & 0 & 0 & 0 \\
                                 0 & 1 & 0 & 0 \\
                                 0 & 0 & 1 & 0 \\
                                 0 & 0 & 0 & 1
             \end{bmatrix}
$$


O inverso dessa matriz, se existe, é tal que ${\bf A}^{-1}\cdot {\bf A} = {\bf I}$. $a_{ij}$ se refer  a um elemento da matriz na fila $i$ e na columna $j$.  Um vetor é um array  unidimensional, ${\bf x}$, da forma:

###  propriedades matemáticas das matrizes


<table border="1">
<thead>
<tr><th align="center">              Relations               </th> <th align="center">      Name     </th> <th align="center">                            matrix elements                            </th> </tr>
</thead>
<tbody>
<tr><td align="center">   $A = A^{T}$                               </td> <td align="center">   symmetric          </td> <td align="center">   $a_{ij} = a_{ji}$                                                          </td> </tr>
<tr><td align="center">   $A = \left (A^{T} \right )^{-1}$          </td> <td align="center">   real ortogonal    </td> <td align="center">   $\sum_k a_{ik} a_{jk} = \sum_k a_{ki} a_{kj} = \delta_{ij}$                </td> </tr>
<tr><td align="center">   $A = A^{ * }$                             </td> <td align="center">   real matrix        </td> <td align="center">   $a_{ij} = a_{ij}^{ * }$                                                    </td> </tr>
<tr><td align="center">   $A = A^{\dagger}$                         </td> <td align="center">   hermitian          </td> <td align="center">   $a_{ij} = a_{ji}^{ * }$                                                    </td> </tr>
<tr><td align="center">   $A = \left (A^{\dagger} \right )^{-1}$    </td> <td align="center">   unitary            </td> <td align="center">   $\sum_k a_{ik} a_{jk}^{ * } = \sum_k a_{ki}^{ * } a_{kj} = \delta_{ij}$    </td> </tr>
</tbody>
</table>

### Algumas matrizes famosas

  * Diagonal if $a_{ij}=0$ for $i\ne j$

  * Upper triangular if $a_{ij}=0$ for $i > j$

  * Lower triangular if $a_{ij}=0$ for $i < j$

  * Tridiagonal if $a_{ij}=0$ for $|i -j| > 1$





### Propriedades das matrizes


Para uma matriz $N\times N$,   $\mathbf{A}$ as seguintes propriedades são todas equivalentes

  * Se a inversa de $\mathbf{A}$ existe, $\mathbf{A}$ é não singular.

  * A equação  $\mathbf{Ax}=0$ implica $\mathbf{x}=0$.

  * As filas de $\mathbf{A}$ formam uma base de $R^N$.

  * As colunas de $\mathbf{A}$ formam uma base de $R^N$.

  * $\mathbf{A}$ é um produto de matrizes elementares.

  * $0$ não é um autovalor de $\mathbf{A}$.

### Operações matemáticas importantes com matrizes

#### Soma e substração 

<!-- Equation labels as ordinary links -->
<div id="eq:mtxadd"></div>
$$
\begin{equation}
\mathbf{A}= \mathbf{B}\pm\mathbf{C}  \Longrightarrow a_{ij} = b_{ij}\pm c_{ij},
\label{eq:mtxadd} \tag{1}
\end{equation}
$$


#### multiplicação escalar-matriz

<!-- Equation labels as ordinary links -->
<div id="_auto1"></div>
$$
\begin{equation}
\mathbf{A}= \gamma\mathbf{B}  \Longrightarrow a_{ij} = \gamma b_{ij},
\label{_auto1} \tag{2}
\end{equation}
$$

#### Multiplicação vetor-matriz

<!-- Equation labels as ordinary links -->
<div id="eq:vecmtx"></div>

$$
\begin{equation}
\mathbf{y}=\mathbf{Ax}   \Longrightarrow y_{i} = \sum_{j=1}^{n} a_{ij}x_j,
\label{eq:vecmtx} \tag{3}
\end{equation}
$$

#### Multiplicação Matriz-Matriz

<!-- Equation labels as ordinary links -->
<div id="eq:mtxmtx"></div>
$$
\begin{equation}
\mathbf{A}=\mathbf{BC}   \Longrightarrow a_{ij} = \sum_{k=1}^{n} b_{ik}c_{kj},
\label{eq:mtxmtx} \tag{4}
\end{equation}
$$

#### Transposição

<!-- Equation labels as ordinary links -->
<div id="_auto2"></div>

$$
\begin{equation}
\mathbf{A}=\mathbf{B}^T   \Longrightarrow a_{ij} = b_{ji}
\label{_auto2} \tag{5}
\end{equation}
$$

### Operações matemáticas importantes com vetores

#### soma e substração

<!-- Equation labels as ordinary links -->
<div id="_auto3"></div>

$$
\begin{equation}
\mathbf{x}= \mathbf{y}\pm\mathbf{z}  \Longrightarrow x_{i} = y_{i}\pm z_{i},
\label{_auto3} \tag{6}
\end{equation}
$$

#### Multiplicação escalar-vetor

<!-- Equation labels as ordinary links -->
<div id="_auto4"></div>

$$
\begin{equation}
\mathbf{x}= \gamma\mathbf{y}  \Longrightarrow x_{i} = \gamma y_{i},
\label{_auto4} \tag{7}
\end{equation}
$$

#### Multiplicação vetor-vetor (multiplicação de Hadamard)

*note que o resultado é um vetor*

<!-- Equation labels as ordinary links -->
<div id="_auto5"></div>

$$
\begin{equation}
\mathbf{x}=\mathbf{yz}   \Longrightarrow x_{i} = y_{i}z_i,
\label{_auto5} \tag{8}
\end{equation}
$$

#### Produto interno ou produto escalar

*o resultado é um escalar*

<!-- Equation labels as ordinary links -->
<div id="eq:innerprod"></div>

$$
\begin{equation}
x=\mathbf{y}^T\mathbf{z}   \Longrightarrow x = \sum_{j=1}^{n} y_{j}z_{j},
\label{eq:innerprod} \tag{9}
\end{equation}
$$

#### Produto externo

*cujo resultado é uma matriz* 

<!-- Equation labels as ordinary links -->
<div id="eq:outerprod"></div>

$$
\begin{equation}
\mathbf{A}=  \mathbf{yz}^T \Longrightarrow  a_{ij} = y_{i}z_{j},
\label{eq:outerprod} \tag{10}
\end{equation}
$$

#### Norma de um vetor 

<!-- Equation labels as ordinary links -->
<div id="eq:norm"></div>
$$
\begin{equation}
|| {\bf x} ||_p = (|x_1|^p + |x_2|^p + ... + |x_n|^p )^{1/p} 
\label{eq:norm} \tag{11}
\end{equation}
$$

#### Relação de Cauchy-Schwartz 

para todo ${\bf x}$ real ou complexo, o produto interno satisfaz:

$$
\begin{equation}
|{\bf x}^T {\bf y}| \le ||x||_2 ||y||_2
\label{eq:cauchy1} \tag{12}
\end{equation}
$$

a partir da qual temos que para todos ${\bf x}$ e ${\bf y}$, o produto escalar satisfaz 

$$
\begin{equation}
||{\bf x} + {\bf y}|| \le ||x||_2 + ||y||_2
\label{eq:cauchy2} \tag{13}
\end{equation}
$$.


### Declaração de matrices 

Em `numpy` declaramos as matrices como arrays multidimensionais:


In [1]:
import numpy as np

In [20]:
A = np.array([[1,3,4],[3,4,6],[4,6,8]])
A

array([[1, 3, 4],
       [3, 4, 6],
       [4, 6, 8]])

In [10]:
B = np.array([2,4,6])
B

array([2, 4, 6])

In [15]:
A.dot(B)

array([ 28,  64, 100])

Devemos ser cuidadosos ao trabalhar com matrices em Python, pois Python, assim como C e C++, organiza as matrices na memoria considerando primeiro as filas (*row major*). Fortran organiza as matrices começando pelas colunas (*column major*). 

As figuras seguintes ilustram ambos esquemas:


<img src="Figs/decl-both2.png" width=80% >
<img src="Figs/decl-both.png" width=80% >

## Atividade

1. Vamos agora usar a equação (4) para multiplicar duas matrices. Começamos com duas matrices pequenas, a matriz A definida acima, e a matriz C:

In [ ]:
C = np.array([[-1,  0,  0.5],[0, -2,  1.5],[ 0.5,  1.5, -1.25]])
C

2. Quando verificarmos que nossa rotina funciona, vamos fazer operações computacionalmente mais exigentes, vamos criar matrizes $n \times n$ com $n = 100$. 

3. Utilizando o módulo `time` vamos comparar a velocidade da função criada por vcs com as rotinas do numpy `matmul` e `dot`. Grafique o tempo usado por cada rotina como função de $n$, para $n=10,100,1000,10000$.

4. Escreva suas conclusões

In [8]:
import time

n = 1000
s = 1./np.sqrt(float(n))
a1 = np.zeros([n,n])

for i in range(n):
    for j in range(n):
        angulo = 2.*np.pi*(i-1)*(j-1)/float(n)
        a1[i,j] = s * (np.sin(angulo) + np.cos(angulo))
        
b1 = np.copy(a1)
t = time.time()
c1 = np.matmul(a1,b1)
t = time.time() - t
print('tempo usado = ', t)

tempo usado =  0.01886749267578125


In [6]:
t = time.time()
d1 = np.dot(a1,b1)
t = time.time() - t
print('tempo usado = ', t)

tempo usado =  0.028328418731689453
